sudo: false

os:
  - linux

language:
  - c

services:
  - docker

before_install:
  - docker pull dockcross/linux-arm64

script:
  - echo FROM dockcross/linux-arm64 > Dockerfile
  - echo sudo apt-get install -y python3 >> Dockerfile
  - echo RUN pip3 install --user meson >> Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t withgit .
  - docker run withgit /bin/sh -c "cd /root && TRAVIS=true meson --cross-file=cross/aarch64.txt build && ninja -C build"
